version: '3'
services:
  eureka-server:
    image: eureka-server
    ports:
     - "8761:8761"
  account-service:
    image: account-service
    depends_on:
     - eureka-server
    deploy:
      mode: replicated
      replicas: 1
  transaction-service:
    image: transaction-service
    depends_on:
     - eureka-server
    deploy:
      mode: replicated
      replicas: 1
  zuul-server:
    image: zuul-server
    depends_on:
     - eureka-server
    ports:
     - "9090:9090"
